AUGMENTATION: True

IMAGE_SIZE: [ 224, 224, 3 ]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 20
CLASSES: [6, 5, 4, 3, 5, 3, 3, 3, 5, 7, 3, 3, 8, 8, 8, 8, 8, 8]
WEIGHTS: imagenet
LEARNING_RATE: 0.001
FINE_TUNE_LEARNING_RATE: 0.00001
FINE_TUNE_EPOCHS: 10
FREEZE_TILL: 30