AUGMENTATION: True

IMAGE_SIZE: [ 224, 224, 3 ]
BATCH_SIZE: 16
INCLUDE_TOP: False
EPOCHS: 20
CLASSES: 18
WEIGHTS: imagenet
LEARNING_RATE: 0.001
FINE_TUNE_LEARNING_RATE: 0.00001
FINE_TUNE_EPOCHS: 10
FREEZE_TILL: 30